# Generated by Django 5.2.11 on 2026-02-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
