# Generated by Django 5.2.11 on 2026-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookings', '0002_bus_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
