# Generated by Django 5.2.11 on 2026-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookings', '0003_bus_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveBigIntegerField(),
        ),
    ]
