# Generated by Django 5.2.11 on 2026-02-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookings', '0004_alter_bus_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
