# Generated by Django 5.2.11 on 2026-02-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busbookings', '0005_bus_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='available_seats',
        ),
    ]
